name: AWS GPU

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "cirun-aws-gpu--${{ github.run_id }}"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2

      - name: Nvidia SMI sanity check
        run: nvidia-smi

      - uses: mamba-org/setup-micromamba@v1
        with:
          log-level: debug
          environment-name: anndatagpu
          micromamba-version: "1.3.1-0"
          create-args: >-
            python=3.10
            cupy
          init-shell: >-
            bash
        env:
          ACTIONS_STEP_DEBUG: true
          CONDA: /home/runnerx/mamba
      - name: Install AnnData
        run: pip install .[dev,test]

      - name: Mamba list
        run: micromamba list

      - name: Run test
        run: python3 -c 'import anndata, cupyx; cupyx.scipy.sparse.random(100, 50, format="csr")'
