name: AWS GPU

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "cirun-aws-gpu--${{ github.run_id }}"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nvidia SMI sanity check
        run: nvidia-smi

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          mamba-version: "latest"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anndata-gpu-ci
          environment-file: etc/example-environment.yml
      
      - name: Install cupy
        run: mamba install cupy

      - name: Install AnnData
        run: pip install .[dev,test]

      - name: Mamba list
        run: micromamba list

      - name: Run test
        run: python3 -c 'import anndata, cupyx; cupyx.scipy.sparse.random(100, 50, format="csr")'
